# Generated by Django 2.2.24 on 2022-05-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='buoy_id',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_agency',
            field=models.CharField(default='', max_length=100),
        ),
    ]
