# Generated by Django 2.2.24 on 2022-05-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0002_auto_20220523_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
