# Generated by Django 2.2.24 on 2022-05-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0003_auto_20220523_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='post_name',
        ),
    ]
