# Generated by Django 2.2.24 on 2022-05-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0005_auto_20220523_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_post',
            new_name='post',
        ),
    ]
