# Generated by Django 2.2.24 on 2022-05-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0006_auto_20220523_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='user',
        ),
    ]
