# Generated by Django 2.2.24 on 2022-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0007_auto_20220523_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
