# Generated by Django 2.2.24 on 2022-05-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0008_auto_20220523_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published_date']},
        ),
    ]
