# Generated by Django 2.2.24 on 2022-05-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0009_auto_20220524_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
