# Generated by Django 2.2.24 on 2022-05-26 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buoys_app', '0011_auto_20220524_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_agency',
        ),
        migrations.AddField(
            model_name='comment',
            name='agency',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
