# Generated by Django 2.2.24 on 2022-05-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0013_auto_20220525_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='agency',
            new_name='user_agency',
        ),
    ]
