# Generated by Django 2.2.24 on 2022-05-26 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0016_auto_20220525_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_agency',
        ),
    ]
