# Generated by Django 2.2.24 on 2022-05-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0017_remove_comment_user_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_agency',
            field=models.CharField(default='', max_length=100),
        ),
    ]
