# Generated by Django 2.2.24 on 2022-05-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0018_comment_user_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_agency',
            field=models.CharField(max_length=100),
        ),
    ]
