# Generated by Django 2.2.24 on 2022-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0020_remove_comment_user_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='agency',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
