# Generated by Django 2.2.24 on 2022-05-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0022_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
