# Generated by Django 2.2.24 on 2022-05-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0023_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='text',
        ),
    ]
