# Generated by Django 2.2.24 on 2022-05-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0024_auto_20220526_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
    ]
