# Generated by Django 2.2.24 on 2022-05-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0026_auto_20220526_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published_date']},
        ),
    ]
