# Generated by Django 2.2.24 on 2022-06-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0028_auto_20220605_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='agency'),
        ),
    ]
