# Generated by Django 2.2.24 on 2022-06-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buoys_app', '0029_auto_20220605_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agency',
            field=models.CharField(max_length=50, verbose_name='agency'),
        ),
    ]
